import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./CartContext";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <div className="flex flex-col min-h-screen min-w-screen overflow-hidden">
            <Header />
            <main className="flex w-full flex-col flex-grow px-4 py-2">
              {children}
            </main>
            <footer className="flex w-full px-4 py-2 flex-shrink-0 justify-center items-center">
              <p className="text-sm text-gray-500">
                Copyright © 2026 Pizzamore. All rights reserved.
              </p>
            </footer>
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
